now=new Date();
let birthday= new Date(2004,5,15);
console.log(birthday.toDateString());
console.log(now.toDateString());
console.log(birthday.getFullYear());
console.log(now.getFullYear());
birthday.setFullYear(2024);
console.log(birthday.toDateString());
let f=["apple","banana"];
console.log(f.push("mango"));
console.log(f.unshift("kiwi"));
console.log(f.splice(2,1,"pear"));
let num=[4,9,16,6,100];
console.log(num.find(n=>n>10));
console.log(num.sort());
console.log(num.sort((a,b)=>a-b));
console.log(num.sort((a,b)=>b-a));
let a=[1,2,3,4,4,4,4,4];
let s1= new Set(a);
console.log(s1);
let s=new Set({});
s.add("blue");
s.delete("blue");
console.log(s);
